from sqlalchemy import Column, Integer, String, Boolean, Text, DateTime, ForeignKey
from sqlalchemy.sql import func
from app.database import Base

class Customer(Base):
    __tablename__ = "customers"

    id = Column(Integer, primary_key=True, index=True)
    customer_code = Column(String(50), nullable=True, index=True)  # e.g., RWP, ISB, KAR
    policy_id = Column(Integer)
    cost_center_id = Column(Integer)
    agent_id = Column(Integer)

    customer_name = Column(String(255), nullable=True)
    customer_type = Column(String(100), default="Company", nullable=True)
    customer_group = Column(String(100), default="Commercial", nullable=True)
    territory = Column(String(100), default="Pakistan", nullable=True)
    salutation = Column(String(100), nullable=True)
    gender = Column(String(100), nullable=True)
    lead_name = Column(String(255), nullable=True)
    opportunity_name = Column(String(255), nullable=True)
    account_manager = Column(String(255), nullable=True)
    image = Column(Text, nullable=True)
    default_price_list = Column(String(255), nullable=True)
    default_bank_account = Column(String(255), nullable=True)
    default_currency = Column(String(50), nullable=True)
    is_internal_customer = Column(Integer, default=0)
    represents_company = Column(String(255), nullable=True)
    market_segment = Column(String(255), nullable=True)
    industry = Column(String(255), nullable=True)
    customer_pos_id = Column(String(255), nullable=True)
    website = Column(String(255), nullable=True)
    language = Column(String(50), default="en")
    customer_details = Column(Text, nullable=True)
    customer_primary_contact = Column(String(255), nullable=True)
    mobile_no = Column(String(50), nullable=True)
    email_id = Column(String(255), nullable=True)
    customer_primary_address = Column(Text, nullable=True)
    primary_address = Column(Text, nullable=True)
    tax_id = Column(String(100), nullable=True)
    tax_category = Column(String(100), nullable=True)
    tax_withholding_category = Column(String(100), nullable=True)
    payment_terms = Column(String(255), nullable=True)
    loyalty_program = Column(String(255), nullable=True)
    loyalty_program_tier = Column(String(255), nullable=True)
    default_sales_partner = Column(String(255), nullable=True)
    default_commission_rate = Column(Integer, default=0)
    so_required = Column(Integer, default=0)
    dn_required = Column(Integer, default=0)
    is_frozen = Column(Integer, default=0)
    disabled = Column(Integer, default=0)
    _user_tags = Column(Text, nullable=True)
    _comments = Column(Text, nullable=True)
    _assign = Column(Text, nullable=True)
    _liked_by = Column(Text, nullable=True)
    
    # Custom Fields
    custom_ntn_number = Column(String(255), nullable=True)
    custom_technical_poc = Column(String(255), nullable=True)
    custom_aend_address = Column(String(255), nullable=True)
    custom_bend_address = Column(String(255), nullable=True)
    custom_static_ip = Column(String(255), nullable=True)
    custom_vlan_id = Column(Integer, default=0)
    custom_handover_point = Column(String(255), nullable=True)
    custom_bandwidth_type = Column(String(255), nullable=True)
    custom_aggregated_port_speed = Column(String(255), nullable=True)
    
    city = Column(String(100), nullable=True)
    address_line_2 = Column(String(255), nullable=True)
    state = Column(String(100), nullable=True)
    zip_code = Column(String(50), nullable=True)
    country = Column(String(100), default="Pakistan", nullable=True)

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
    created_by = Column(Integer, nullable=True)